CREATE TABLE ROOM (
  ROOM_ID     BIGINT AUTO_INCREMENT PRIMARY key,
  NAME        VARCHAR(16) NOT null,
  ROOM_NUMBER char(2)     NOT NULL UNIQUE,
  BED_INFO    char(2)     NOT NULL
);

CREATE TABLE GUEST (
  GUEST_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME    VARCHAR(64),
  LAST_NAME     varchar(64),
  EMAIL_ADDRESS varchar(64),
  ADDRESS       varchar(64),
  COUNTRY       varchar(32),
  STATE         varchar(12),
  PHONE_NUMBER  varchar(24)
);

CREATE TABLE RESERVATION (
  RESERVATION_ID BIGINT auto_increment primary key,
  ROOM_ID        BIGINT not null,
  GUEST_ID       BIGINT NOT NULL,
  RES_DATE       DATE
);

ALTER TABLE RESERVATION
  ADD FOREIGN KEY (ROOM_ID) REFERENCES ROOM (ROOM_ID);
ALTER TABLE RESERVATION
  ADD FOREIGN KEY (GUEST_ID) REFERENCES GUEST (GUESt_ID);
CREATE INDEX IDX_RES_DATE_
  ON RESERVATION (RES_DATE);